// Package titleclass classifies job titles into department buckets for
// red-team target prioritization.
//
// It is a pure-Go port of the job-classifier tool: a character n-gram TF-IDF
// vectorizer feeding a multinomial logistic-regression head. The trained model
// (vocabulary, IDF weights, coefficients, and the abbreviation map) is embedded
// from model.json, so there is no CGo, no model download, and the whole thing
// ships inside the brutus binary and cross-compiles cleanly.
//
// The model is generated by job-classifier/train_go.py; see that directory for
// how the corpus and weights are produced. The inference math here mirrors
// scikit-learn's TfidfVectorizer(analyzer="char_wb") + LogisticRegression
// exactly and is locked to the Python output by titleclass_test.go.
package titleclass

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"strings"
	"sync"
)

//go:embed model.json
var modelBytes []byte

// model is the on-disk representation exported by train_go.py.
type model struct {
	Classes          []string          `json:"classes"`
	UnknownLabel     string            `json:"unknown_label"`
	NgramMin         int               `json:"ngram_min"`
	NgramMax         int               `json:"ngram_max"`
	DefaultThreshold float64           `json:"default_threshold"`
	Abbreviations    map[string]string `json:"abbreviations"`
	Vocabulary       map[string]int    `json:"vocabulary"`
	IDF              []float64         `json:"idf"`
	Coef             [][]float64       `json:"coef"`      // [class][feature]
	Intercept        []float64         `json:"intercept"` // [class]
}

// Classifier maps a job title to a department. It is safe for concurrent use.
type Classifier struct {
	m *model
}

// Result is a single classification outcome.
type Result struct {
	Title      string  // the input title, unchanged
	Department string  // predicted department, or UnknownLabel below threshold
	Confidence float64 // top softmax probability
	Argmax     string  // highest-probability class ignoring the threshold
	// Probabilities is the full per-department distribution (sums to ~1).
	Probabilities map[string]float64
}

var (
	// Mirrors categories.normalize in the Python tool. \s is ASCII whitespace,
	// which is all job titles contain in practice.
	punctRe = regexp.MustCompile(`[^a-z0-9\s]`)
	wsRe    = regexp.MustCompile(`\s+`)
)

// New loads the embedded model and returns a ready classifier.
func New() (*Classifier, error) {
	var m model
	if err := json.Unmarshal(modelBytes, &m); err != nil {
		return nil, fmt.Errorf("titleclass: parsing embedded model: %w", err)
	}
	if len(m.Classes) == 0 || len(m.Coef) != len(m.Classes) {
		return nil, fmt.Errorf("titleclass: embedded model is malformed")
	}
	return &Classifier{m: &m}, nil
}

var (
	defaultOnce sync.Once
	defaultClf  *Classifier
	defaultErr  error
)

// Default returns a process-wide shared classifier, loaded once.
func Default() (*Classifier, error) {
	defaultOnce.Do(func() { defaultClf, defaultErr = New() })
	return defaultClf, defaultErr
}

// UnknownLabel is the department assigned to below-threshold predictions.
func (c *Classifier) UnknownLabel() string { return c.m.UnknownLabel }

// DefaultThreshold is the confidence cutoff used by Classify.
func (c *Classifier) DefaultThreshold() float64 { return c.m.DefaultThreshold }

// Normalize lowercases, expands "&", strips punctuation, collapses whitespace,
// and expands known abbreviations — matching categories.normalize in Python.
func (c *Classifier) Normalize(title string) string {
	text := strings.ToLower(title)
	text = strings.ReplaceAll(text, "&", " and ")
	text = punctRe.ReplaceAllString(text, " ")
	text = strings.TrimSpace(wsRe.ReplaceAllString(text, " "))
	if text == "" {
		return ""
	}
	toks := strings.Split(text, " ")
	for i, tok := range toks {
		if exp, ok := c.m.Abbreviations[tok]; ok {
			toks[i] = exp
		}
	}
	return strings.Join(toks, " ")
}

// Classify classifies a title using the model's default threshold.
func (c *Classifier) Classify(title string) Result {
	return c.ClassifyWithThreshold(title, c.m.DefaultThreshold)
}

// ClassifyWithThreshold classifies a title, labeling it Unknown when the top
// probability is below threshold.
func (c *Classifier) ClassifyWithThreshold(title string, threshold float64) Result {
	probs := c.distribution(c.Normalize(title))

	top := 0
	for i, p := range probs {
		if p > probs[top] {
			top = i
		}
	}
	conf := probs[top]
	argmax := c.m.Classes[top]

	dept := argmax
	if conf < threshold {
		dept = c.m.UnknownLabel
	}

	pm := make(map[string]float64, len(probs))
	for i, p := range probs {
		pm[c.m.Classes[i]] = p
	}
	return Result{
		Title:         title,
		Department:    dept,
		Confidence:    conf,
		Argmax:        argmax,
		Probabilities: pm,
	}
}

// distribution runs the TF-IDF + logistic-regression + softmax pipeline on an
// already-normalized title, returning the per-class probabilities.
func (c *Classifier) distribution(norm string) []float64 {
	// Character n-gram counts restricted to the known vocabulary.
	counts := make(map[int]float64)
	for _, gram := range charWBNgrams(norm, c.m.NgramMin, c.m.NgramMax) {
		if idx, ok := c.m.Vocabulary[gram]; ok {
			counts[idx]++
		}
	}

	// tf-idf weighting followed by L2 normalization (norm="l2").
	vec := make(map[int]float64, len(counts))
	var sumSq float64
	for idx, tf := range counts {
		v := tf * c.m.IDF[idx]
		vec[idx] = v
		sumSq += v * v
	}
	if sumSq > 0 {
		inv := 1.0 / math.Sqrt(sumSq)
		for idx := range vec {
			vec[idx] *= inv
		}
	}

	// Logits = intercept + coef · x, then softmax (matches predict_proba for a
	// multinomial LogisticRegression).
	logits := make([]float64, len(c.m.Classes))
	for cl := range c.m.Classes {
		s := c.m.Intercept[cl]
		row := c.m.Coef[cl]
		for idx, v := range vec {
			s += row[idx] * v
		}
		logits[cl] = s
	}
	return softmax(logits)
}

// charWBNgrams reproduces scikit-learn's CountVectorizer/_char_wb_ngrams: for
// each whitespace-delimited word, pad with a space on each side and emit every
// n-gram for n in [minN, maxN]. A word shorter than n is emitted once (the
// offset==0 break), which also stops larger n for that word.
func charWBNgrams(text string, minN, maxN int) []string {
	var out []string
	for _, word := range strings.Fields(text) {
		w := []rune(" " + word + " ")
		wlen := len(w)
		for n := minN; n <= maxN; n++ {
			end := n
			if end > wlen {
				end = wlen
			}
			out = append(out, string(w[:end]))
			offset := 0
			for offset+n < wlen {
				offset++
				out = append(out, string(w[offset:offset+n]))
			}
			if offset == 0 {
				break
			}
		}
	}
	return out
}

// softmax converts logits to a probability distribution, subtracting the max
// for numerical stability.
func softmax(logits []float64) []float64 {
	max := logits[0]
	for _, v := range logits {
		if v > max {
			max = v
		}
	}
	out := make([]float64, len(logits))
	var sum float64
	for i, v := range logits {
		e := math.Exp(v - max)
		out[i] = e
		sum += e
	}
	for i := range out {
		out[i] /= sum
	}
	return out
}
