#!/usr/bin/env python3
"""Generate synthetic job-title training data via the Anthropic API.

For each trainable department, ask the model for ~150 realistic, varied job
titles, then deduplicate, shuffle, and write ``data/titles.csv`` with columns
``title,department``.

Requires ``ANTHROPIC_API_KEY`` in the environment (never hardcoded).

    python generate_data.py                    # default 150 per category
    python generate_data.py --per-category 120 # override count
    python generate_data.py --model claude-sonnet-4-6

Note: inside the brutus workflow the initial dataset is generated by delegating
to Claude Code sub-agents (no API key needed). This script is the reproducible,
key-based equivalent for anyone regenerating the corpus standalone or on CI.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import re
import sys
import time
from pathlib import Path

from categories import DEPARTMENTS

try:
    import anthropic
except ImportError:  # pragma: no cover - dependency guard
    sys.exit("anthropic SDK not installed. Run: pip install -r requirements.txt")

try:
    from tqdm import tqdm
except ImportError:  # pragma: no cover - dependency guard
    sys.exit("tqdm not installed. Run: pip install -r requirements.txt")

DATA_DIR = Path(__file__).resolve().parent / "data"
OUTPUT_CSV = DATA_DIR / "titles.csv"
DEFAULT_MODEL = "claude-sonnet-4-6"

SYSTEM_PROMPT = (
    "You are generating synthetic training data for a job title classifier.\n"
    "Respond only with a JSON array of strings. No preamble, no markdown fences.\n"
    "Generate realistic, varied job titles — mix seniority levels, include common\n"
    "abbreviations, regional variants, and edge cases that genuinely belong to\n"
    "this category. Avoid obvious/generic titles, favor the long tail."
)

_FENCE_RE = re.compile(r"^```(?:json)?\s*|\s*```$", re.MULTILINE)


def build_user_prompt(department: str, guidance: str, count: int) -> str:
    return (
        f"Category: {department}\n"
        f"Definition: {guidance}\n\n"
        f"Generate {count} distinct, realistic job titles that genuinely belong to "
        f"the '{department}' category. Include seniority variations "
        f"(Analyst/Manager/Director/VP/SVP/C-level), common abbreviations, regional "
        f"naming conventions, and genuinely ambiguous-but-correct edge cases. "
        f"Return only a JSON array of {count} strings."
    )


def parse_titles(raw: str) -> list[str]:
    """Extract a JSON array of strings from the model response, tolerating fences."""
    cleaned = _FENCE_RE.sub("", raw).strip()
    data = json.loads(cleaned)
    if not isinstance(data, list):
        raise ValueError("response was not a JSON array")
    out: list[str] = []
    for item in data:
        if isinstance(item, str) and item.strip():
            out.append(item.strip())
    return out


def request_titles(
    client: "anthropic.Anthropic",
    model: str,
    department: str,
    guidance: str,
    count: int,
    max_retries: int = 5,
) -> list[str]:
    """One category worth of titles, with exponential-backoff retry."""
    user_prompt = build_user_prompt(department, guidance, count)
    delay = 2.0
    last_err: Exception | None = None
    for attempt in range(1, max_retries + 1):
        try:
            resp = client.messages.create(
                model=model,
                max_tokens=8000,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_prompt}],
            )
            text = "".join(
                block.text for block in resp.content if block.type == "text"
            )
            return parse_titles(text)
        except (anthropic.APIStatusError, anthropic.APIConnectionError) as err:
            last_err = err
            # 4xx that aren't rate limits won't fix themselves — fail fast.
            status = getattr(err, "status_code", None)
            if status is not None and 400 <= status < 500 and status != 429:
                raise
        except (json.JSONDecodeError, ValueError) as err:
            last_err = err  # transient bad parse; retry asks again
        if attempt < max_retries:
            time.sleep(delay)
            delay *= 2
    raise RuntimeError(
        f"failed to generate titles for '{department}' after {max_retries} "
        f"attempts: {last_err}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--per-category", type=int, default=150,
                        help="titles to request per department (default: 150)")
    parser.add_argument("--model", default=DEFAULT_MODEL,
                        help=f"Anthropic model id (default: {DEFAULT_MODEL})")
    parser.add_argument("--seed", type=int, default=1337,
                        help="shuffle seed for reproducibility")
    args = parser.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("ANTHROPIC_API_KEY is not set in the environment.")

    client = anthropic.Anthropic()
    random.seed(args.seed)

    # dept -> title, deduped case-insensitively while preserving first spelling.
    labeled: list[tuple[str, str]] = []
    seen: set[str] = set()

    for department, guidance in tqdm(DEPARTMENTS.items(), desc="categories"):
        titles = request_titles(
            client, args.model, department, guidance, args.per_category
        )
        for title in titles:
            key = title.lower().strip()
            if key and key not in seen:
                seen.add(key)
                labeled.append((title, department))

    random.shuffle(labeled)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with OUTPUT_CSV.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["title", "department"])
        writer.writerows(labeled)

    print(f"Wrote {len(labeled)} unique labeled titles to {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
