name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci*'
      - 'Makefile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: praetorian-inc/public-workflows/.github/workflows/go-ci.yml@dc359d4cf6ade393f811c13533b1a3abb780f5d1  # v2.16.7
    permissions:
      contents: read
    with:
      build-cmd-path: ./cmd/brutus
      build-binary-name: brutus
    secrets: inherit
