name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci*'
      - 'Makefile'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: praetorian-inc/public-workflows/.github/workflows/go-ci.yml@1a91334ad83c70d8a1e8375a925c9b5cd69fb6ec  # v2.18.2
    permissions:
      contents: read
    with:
      build-cmd-path: ./cmd/brutus
      build-binary-name: brutus
    secrets: inherit
